config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :lists, only: [ :index, :show, :new, :create ] do
    resources :bookmarks, only: [:new, :create]
  end
  resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :movie_id, uniqueness: { scope: :list_id }
  validates :comment, length: { minimum: 6 }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks

  validates :name, uniqueness: true, presence: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, uniqueness: true, presence: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
  end

  def create
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(params_bookmark)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy

    redirect_to list_path(@bookmark.list)
  end

  private

  def params_bookmark
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(params_list)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  private

  def params_list
    params.require(:list).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/list_helper.rb
module ListHelper
end

app/views/bookmarks/new.html.erb
<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.input :comment %>
  <%= f.association :movie %>
  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<nav class="navbar navbar-light bg-light">
  <form class="container-fluid justify-content-end">
    <button class="btn btn-outline-success m-2" type="button"><%= link_to "New list", new_list_path %></button>
  </form>
</nav>
<div class="banner">
<h1>Save any kind of movies</h1>
<p>Organise your brain and save movies in nicely ordered lists!</p>
</div>
<h2>Your Lists</h2>

<ul>
  <div class="cards-list">
    <% @lists.each do |list| %>
    <div class="card-list">
      <li><%= link_to list.name, list_path(list) %></li>
    </div>
    <% end %>
  </div>
</ul>

app/views/lists/new.html.erb
<%= simple_form_for(@list) do |f| %>
  <%= f.input :name %>
  <%= f.submit %>
<% end %>

app/views/lists/show.html.erb
<nav class="navbar navbar-light bg-light">
  <form class="container-fluid justify-content-end">
    <button class="btn btn-outline-success m-2" type="button"><%= link_to "Home", lists_path %></button>
    <button class="btn btn-outline-success m-2" type="button"><%= link_to "Add movie", new_list_bookmark_path(@list) %></button>
  </form>
</nav>

<div class="banner-show">
<h1><%= @list.name %></h1>
</div>

<ul>
<div class="cards-show">
  <% @list.bookmarks.each_with_index do |bookmark, index| %>
    <div class="card-show">
      <h3><%= index + 1 %> <%= bookmark.movie.title %></h3>
      <img src= <% bookmark.movie.poster_url%> />
      <li><em>description:</em> <%= bookmark.movie.overview %></li>
      <li><em>rating:</em> <%= bookmark.movie.rating %></li>
      <button class="btn btn-outline-success m-2" type="button"><%= link_to "Remove",
                      bookmark_path(bookmark),
                      method: :delete,
                      data: { confirm: "Are you sure?" } %></button>
    </div>
  <% end %>
</div>
</ul>